changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes
      labels:
        - breaking
        - Semver-Major
    - title: Features
      labels:
        - feature
        - enhancement
        - Semver-Minor
    - title: Fixes
      labels:
        - fix
        - bug
    - title: Other Changes
      labels:
        - "*"
